### ISSUE TITLE
Ctrl+Alt+Z shortcut behavior changes

### ISSUE THREAD

**Issue by tanmatra** [comod/git-scope#10]
In IDEA without this plugin:
Pressing Ctrl+Alt+Z when inside changed lines (highlighted in editor gutter) - rollbacks only changed lines;
Outside changed lines - dialog prompts to rollback whole file.

With this plugin: only the second behavior works.

**Comment by MikhailAsadchyIDT** [comment]
Same issue. 

[Rollback lines](https://yadi.sk/i/iAJl7Ig_T0l3rA) functionality doesn't work with the plugin enabled. And shows error 
java.lang.NoSuchFieldError: myTracker
	at implementation.lineStatusTracker.MyLineStatusTrackerManager$MyLineStatusMarkerRenderer.access$000(MyLineStatusTrackerManager.java:39)
	at implementation.lineStatusTracker.MyLineStatusTrackerManager$MyLineStatusMarkerRenderer$MyRollbackLineStatusRangeAction.actionPerformed(MyLineStatusTrackerManager.java:69)
	at com.intellij.openapi.vcs.ex.LineStatusMarkerPopupRenderer$RangeMarkerAction.actionPerformed(LineStatusMarkerPopupRenderer.java:220)
	at implementation.lineStatusTracker.MyLineStatusTrackerManager$MyLineStatusMarkerRenderer$MyRollbackLineStatusRangeAction.actionPerformed(MyLineStatusTrackerManager.java:57)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:281)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:209)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:177)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:160)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:477)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:911)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by comod** [comment]
#11

**Comment by tanmatra** [comment]
Not fixed in 3.0.4 for Ctrl+Alt+Z keystroke.
