### ISSUE TITLE
Target branch popup from other projects keeps showing when using PhpStorm + Git Scope when using multiple virtual desktops

### ISSUE THREAD

**Issue by Wotuu** [comod/git-scope#13]
I have multiple PhpStorm instances open across multiple virtual desktops to keep certain projects separate from one another with separate browsers etc. I installed this plugin yesterday - and it's something I can see myself using. Right now there is one crippling bug where if I'm working in PhpStorm in Virtual Desktop A, very frequently the `target branch` selector where you can select branches will pop up _from a project in another Virtual Desktop_. Right now, when I hit ctrl + s to save my file the `target file` popup even shows up from the very same project which is very annoying.

Talking about this window which keeps popping up all the time making this very much unusable.
![image](https://user-images.githubusercontent.com/811809/105331822-2eb8f600-5bd4-11eb-9a2f-e1700ceed604.png)

**Comment by markus-ksg** [comment]
I see the same problem with a single PhpStorm instance but multiple Git repositories in my project.

**Comment by marthinwurer** [comment]
I have the same issue with multiple git repos in a single CLion instance.

**Comment by pranaypatel77** [comment]
Same here.  It's super annoying as it takes focus and flashes like crazy.   It's unusable - which sucks because I used to rely on GitScope so much.

**Comment by Northnroro** [comment]
Same here. I'm facing this in GoLand. It happens when opening a file and when saving a file.

Error log when saving:
```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at implementation.targetBranchWidget.BranchActionGroupPopup.processOnSizeChanged(BranchActionGroupPopup.java:167)
	at implementation.targetBranchWidget.BranchActionGroupPopup.access$300(BranchActionGroupPopup.java:47)
	at implementation.targetBranchWidget.BranchActionGroupPopup$4.componentResized(BranchActionGroupPopup.java:150)
	at java.desktop/java.awt.AWTEventMulticaster.componentResized(AWTEventMulticaster.java:167)
	at java.desktop/java.awt.Component.processComponentEvent(Component.java:6478)
	at java.desktop/java.awt.Component.processEvent(Component.java:6432)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Window.processEvent(Window.java:2061)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Error log when opening:
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'currentRepository' of implementation/targetBranchWidget/MyGitBranchPopup.getInstance must not be null
	at implementation.targetBranchWidget.MyGitBranchPopup.$$$reportNull$$$0(MyGitBranchPopup.java)
	at implementation.targetBranchWidget.MyGitBranchPopup.getInstance(MyGitBranchPopup.java)
	at ui.elements.TargetBranchPanel.lambda$showPopup$0(TargetBranchPanel.java:147)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by hoxi** [comment]
Please test and comment if this issue still is valid on the 2025.x release of the plugin.
