### ISSUE TITLE
2021.1 EAP: Assertion failed: dataContext has no component for new ListPopupStep

### ISSUE THREAD

**Issue by InvisibleSmiley** [comod/git-scope#14]
```
java.lang.Throwable: Assertion failed: dataContext has no component for new ListPopupStep
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:197)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.createStep(PopupFactoryImpl.java:275)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.<init>(PopupFactoryImpl.java:216)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.<init>(PopupFactoryImpl.java:183)
	at com.intellij.openapi.vcs.ui.FlatSpeedSearchPopup.<init>(FlatSpeedSearchPopup.java:37)
	at implementation.targetBranchWidget.BranchActionGroupPopup.<init>(BranchActionGroupPopup.java:67)
	at implementation.targetBranchWidget.MyBranchActionGroupPopup.<init>(MyBranchActionGroupPopup.java:56)
	at implementation.targetBranchWidget.MyDvcsBranchPopup.<init>(MyDvcsBranchPopup.java:65)
	at implementation.targetBranchWidget.MyGitBranchPopup.<init>(MyGitBranchPopup.java:57)
	at implementation.targetBranchWidget.MyGitBranchPopup.getInstance(MyGitBranchPopup.java:46)
	at ui.elements.TargetBranchPanel$2.mouseClicked(TargetBranchPanel.java:84)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:277)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6655)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by geoffreywiseman** [comment]
Just got this in my IDE on 2021.1 final:
> IntelliJ IDEA 2021.1 (Ultimate Edition)
> Build #IU-211.6693.111, built on April 6, 2021

**Comment by eekboom** [comment]
Can confirm. 
Also there is no "Git Scope" toolwindow anywhere.

**Comment by Faldrian** [comment]
> Can confirm.
> Also there is no "Git Scope" toolwindow anywhere.

Using 2021.1.1, I can clearly see the "Git Scope" tool window. Maybe you have to activate it via "View -> Tool Windows -> Git Scope"

**Comment by gspencergoog** [comment]
I have the same or very similar issue in 2021.2:

The Git Scope tab is there and functional, but once I try and select the branch to compare with, I get this stack trace, and I get the popup for the list of branches showing up , but then it flickers and doesn't go away until I click outside the window.

```
java.lang.Throwable: Assertion failed: dataContext has no component for new ListPopupStep
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:218)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.createStep(PopupFactoryImpl.java:272)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.<init>(PopupFactoryImpl.java:215)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.<init>(PopupFactoryImpl.java:182)
	at com.intellij.openapi.vcs.ui.FlatSpeedSearchPopup.<init>(FlatSpeedSearchPopup.java:34)
	at implementation.targetBranchWidget.BranchActionGroupPopup.<init>(BranchActionGroupPopup.java:67)
	at implementation.targetBranchWidget.MyBranchActionGroupPopup.<init>(MyBranchActionGroupPopup.java:56)
	at implementation.targetBranchWidget.MyDvcsBranchPopup.<init>(MyDvcsBranchPopup.java:65)
	at implementation.targetBranchWidget.MyGitBranchPopup.<init>(MyGitBranchPopup.java:57)
	at implementation.targetBranchWidget.MyGitBranchPopup.getInstance(MyGitBranchPopup.java:46)
	at ui.elements.TargetBranchPanel.lambda$showPopup$0(TargetBranchPanel.java:147)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

With an induced stack of:
```
Following exceptions happened soon after this one, most probably they are induced.


2021-07-27T14:48:43.076
java.lang.NoSuchMethodError: 'void implementation.targetBranchWidget.BranchActionGroupPopup.addPopupListener(com.intellij.openapi.ui.popup.JBPopupListener)'
	at implementation.targetBranchWidget.BranchActionGroupPopup.trackDimensions(BranchActionGroupPopup.java:155)
	at implementation.targetBranchWidget.BranchActionGroupPopup.afterShow(BranchActionGroupPopup.java:236)
	at com.intellij.ui.popup.AbstractPopup.lambda$show$10(AbstractPopup.java:1127)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

<details>
<summary>IntelliJ version info</summary>
```
IntelliJ IDEA 2021.2 (Community Edition)
Build #IC-212.4746.92, built on July 27, 2021
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.10.40-1rodete2-amd64
GC: ParNew, ConcurrentMarkSweep
Memory: 7918M
Cores: 72
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: Batch Scripts Support (1.0.12), com.intellij.plugins.macoskeymap (212.4535.15), com.paperetto.dash (3.3), Git Scope (3.0.4), mobi.hsz.idea.gitignore (4.1.1), Dart (212.4746.57), io.flutter (58.0.4), GrepConsole (11.10.211.6086.0), String Manipulation (8.15.203.000.3), PythonCore (212.4746.92)
Kotlin: 212-1.5.10-release-IJ4746.92
Current Desktop: X-Cinnamon
```
</details>

**Comment by comod** [comment]
Thanks for Reporting. I also have this issue and ignore them. Everything else works as expected (for me). But this is on the top of my list. I would also appreciate it if one of you could provide a fix

**Comment by geoffreywiseman** [comment]
Definitely related to [this issue](https://youtrack.jetbrains.com/issue/IDEA-266993), although my understanding of IntelliJ plugin programming is pretty limited, so it would take me a while to figure out if there's an event you could be pulling the context from and if not, which component should be used to get a data context now.

**Comment by comod** [comment]
I have fixed this already. Check the latest (unreleased) Version 3.0.5 (https://github.com/comod/git-scope/tree/2021-10-14). But before i can release this i must fix a few more compatibility issues. Jetbrains declined my update request:

> There are several compatibility issues with the plugin update. You can find more information here. Could you please check the compatibility settings?
> 
> Maybe it makes sense to limit the 'since' version. You can do this on the update page for the current.
> 
> And don't forget to update it in the plugin.xml file for the future versions.

compatibility issues looks like this:
![image](https://user-images.githubusercontent.com/19387282/144743382-4bb09c60-8713-4b34-8a85-15c6c877f59f.png)

**Comment by lkiss80** [comment]
Thanks for the great plugin.  Was curious if there is any progress on getting this resolved and released?
